# Generated by Django 4.0.2 on 2022-02-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Aut', 'Author'), ('Sub', 'Subscriber')], default='Sub', max_length=3),
        ),
    ]
